config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    get '/signup' => 'users#new'
    post '/users' => 'users#create'

  resources :about, only: [:index]

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :categories, except: [:edit, :update, :show, :destroy]
    resources :products, except: [:edit, :update, :show]
  end

end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products

end

app/models/line_item.rb
class LineItem < ApplicationRecord

  belongs_to :order
  belongs_to :product

  monetize :item_price_cents, numericality: true
  monetize :total_price_cents, numericality: true

end

app/models/order.rb
class Order < ApplicationRecord
  
  has_many :line_items

  monetize :total_cents, numericality: true

  validates :stripe_charge_id, presence: true

end

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates_uniqueness_of :email
  validates_length_of :password, minimum:8

  def self.authenticate_with_credentials(email, password)
    user = find_by(email: email.strip.downcase)
    user&.authenticate(password) || nil
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  http_basic_authenticate_with name: Rails.configuration.basic_auth[:username], password: Rails.configuration.basic_auth[:password]

  def show
    @categories = Category.all.order(id: :asc)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  http_basic_authenticate_with name: Rails.configuration.basic_auth[:username], password: Rails.configuration.basic_auth[:password]

  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  private

  def cart
    @cart ||= cookies[:cart].present? ? JSON.parse(cookies[:cart]) : {}
  end
  helper_method :cart

  def enhanced_cart
    @enhanced_cart ||= Product.where(id: cart.keys).map {|product| { product:product, quantity: cart[product.id.to_s] } }
  end
  helper_method :enhanced_cart

  def cart_subtotal_cents
    enhanced_cart.map {|entry| entry[:product].price_cents * entry[:quantity]}.sum
  end
  helper_method :cart_subtotal_cents

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  def update_cart(new_cart)
    cookies[:cart] = {
      value: JSON.generate(new_cart),
      expires: 10.days.from_now
    }
    cookies[:cart]
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # before_action :authorize

  def show
  end

  def add_item
    product_id = params[:product_id].to_s
    modify_cart_delta(product_id, +1)

    redirect_back fallback_location: root_path
  end

  def remove_item
    product_id = params[:product_id].to_s
    modify_cart_delta(product_id, -1)

    redirect_back fallback_location: root_path
  end

  private

  def modify_cart_delta(product_id, delta)
    cart[product_id] = (cart[product_id] || 0) + delta
    cart.delete(product_id) if cart[product_id] < 1
    update_cart cart
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.order(created_at: :desc)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # before_filter :authorize
  def show
    @order = Order.includes(line_items: :product).find(params[:id])

  end

  def create
    charge = perform_stripe_charge
    order  = create_order(charge)

    if order.valid?
      empty_cart!
      redirect_to order, notice: 'Your Order has been placed.'
    else
      redirect_to cart_path, flash: { error: order.errors.full_messages.first }
    end

  rescue Stripe::CardError => e
    redirect_to cart_path, flash: { error: e.message }
  end

  private

  def empty_cart!
    # empty hash means no products in cart :)
    update_cart({})
  end

  def perform_stripe_charge
    Stripe::Charge.create(
      source:      params[:stripeToken],
      amount:      cart_subtotal_cents,
      description: "Jungle Order",
      currency:    'cad'
    )
  end

  def create_order(stripe_charge)
    order = Order.new(
      email: params[:stripeEmail],
      total_cents: cart_subtotal_cents,
      stripe_charge_id: stripe_charge.id, # returned by stripe
    )

    enhanced_cart.each do |entry|
      product = entry[:product]
      quantity = entry[:quantity]
      order.line_items.new(
        product: product,
        quantity: quantity,
        item_price: product.price,
        total_price: product.price * quantity
      )
    end
    order.save!

    # Tell the Mailer to send a receipt email after save
    OrderMailer.with(order: order).order_email.deliver_now
    order
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # If the user exists AND the password entered is correct.
    if user = User.authenticate_with_credentials(params[:email], params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/_form.html.erb
<%= form_with(model: about) do |form| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
        <% about.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :index %>
    <%= form.text_field :index %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/about/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/about/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Abouts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

  </tbody>
</table>

<br>

app/views/about/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/about/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @about.index %>
</p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>

app/views/users/new.html.erb
<section class="users-new">

  <header class="page-header">
    <h1>Sign Up</h1>
  </header>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for :user, url: '/users' do |form| %>

        <div class="form-group">
          <%= form.label :firstname %>
          <%= form.text_field :firstname, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :lastname %>
          <%= form.text_field :lastname, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= form.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :password %>
          <%= form.password_field :password, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :password_confirmation %>
          <%= form.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <%= form.submit 'Submit', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>